server:
 port: 8888
 
spring:
  thymeleaf:
    cache: false

filemanager:
  rootList: C:/,D:/

files:
 docservice:
  url:
    api: http://127.0.0.1/web-apps/apps/api/documents/api.js

fileServer:
 domain: http://10.28.1.136:8888